# Generated by Django 4.1 on 2023-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="census",
            name="adscription_center",
            field=models.CharField(default="", max_length=200),
        ),
    ]
