# Generated by Django 4.1 on 2023-11-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_adscription_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='census',
            name='tags',
            field=models.ManyToManyField(related_name='census', to='census.tag'),
        ),
    ]
