# Generated by Django 4.1 on 2023-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0003_tag_census_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="census",
            options={"verbose_name": "Census"},
        ),
        migrations.AlterField(
            model_name="census",
            name="voter_id",
            field=models.PositiveIntegerField(verbose_name="voter_id"),
        ),
        migrations.AlterField(
            model_name="census",
            name="voting_id",
            field=models.PositiveIntegerField(verbose_name="voting_id"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
