# Generated by Django 4.1 on 2023-11-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0005_voting_seats_voting_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="type",
            field=models.CharField(
                choices=[
                    ("IDENTITY", "Identity"),
                    ("DHONDT", "D'Hondt"),
                    ("WEBSTER", "Webster"),
                ],
                default="IDENTITY",
                max_length=8,
            ),
        ),
    ]
