# Generated by Django 4.1 on 2023-12-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0006_alter_voting_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question"},
        ),
        migrations.AlterModelOptions(
            name="questionoption",
            options={"verbose_name": "QuestionOption"},
        ),
        migrations.AlterModelOptions(
            name="voting",
            options={"verbose_name": "Voting"},
        ),
        migrations.RemoveField(
            model_name="voting",
            name="type",
        ),
        migrations.AddField(
            model_name="voting",
            name="method",
            field=models.CharField(
                choices=[
                    ("IDENTITY", "Identity"),
                    ("DHONDT", "D'Hondt"),
                    ("WEBSTER", "Webster"),
                ],
                default="IDENTITY",
                max_length=8,
                verbose_name="method",
            ),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="option",
            field=models.TextField(verbose_name="option"),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="voting.question",
                verbose_name="question",
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end_date"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voting",
                to="voting.question",
                verbose_name="question",
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="seats",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="seats"
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="start_date"
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="tally",
            field=models.JSONField(blank=True, null=True, verbose_name="tally"),
        ),
    ]
