# Generated by Selenium IDE
from base.tests import BaseTestCase
from django.contrib.auth.models import User
from voting.models import Voting, Question
from census.models import Census
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from django.utils import timezone

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

class TestFiltroname(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()
    options = webdriver.ChromeOptions()
    options.headless = True
    self.driver = webdriver.Chrome(options=options)
    super().setUp()

    self.user = User.objects.filter(username="noadmin").first()

    self.q1 = Question(desc='Question #1')
    self.q1.save()
    self.v1 = Voting(name='Voting #1', question=self.q1, start_date=timezone.now(), end_date=timezone.now())
    self.v1.save()
    self.c1 = Census(voter_id=self.user.id, voting_id=self.v1.id)
    self.c1.save()

    self.q2 = Question(desc='Question #2')
    self.q2.save()
    self.v2 = Voting(name='Voting #2', question=self.q2, start_date=timezone.now())
    self.v2.save()
    self.c2 = Census(voter_id=self.user.id, voting_id=self.v2.id)
    self.c2.save()

    self.q3 = Question(desc='Question #3')
    self.q3.save()
    self.v3 = Voting(name='Voting #3', question=self.q3)
    self.v3.save()
    self.c3 = Census(voter_id=self.user.id, voting_id=self.v3.id)
    self.c3.save()
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()
    self.base.tearDown()
  
  
class TestFiltrofecha(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()
    options = webdriver.ChromeOptions()
    options.headless = True
    self.driver = webdriver.Chrome(options=options)
    super().setUp()

    self.user = User.objects.filter(username="noadmin").first()

    self.q1 = Question(desc='Question #1')
    self.q1.save()
    self.v1 = Voting(name='Voting #1', question=self.q1, start_date=timezone.now(), end_date=timezone.now())
    self.v1.save()
    self.c1 = Census(voter_id=self.user.id, voting_id=self.v1.id)
    self.c1.save()

    self.q2 = Question(desc='Question #2')
    self.q2.save()
    self.v2 = Voting(name='Voting #2', question=self.q2, start_date=timezone.now())
    self.v2.save()
    self.c2 = Census(voter_id=self.user.id, voting_id=self.v2.id)
    self.c2.save()

    self.q3 = Question(desc='Question #3')
    self.q3.save()
    self.v3 = Voting(name='Voting #3', question=self.q3)
    self.v3.save()
    self.c3 = Census(voter_id=self.user.id, voting_id=self.v3.id)
    self.c3.save()
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()
    self.base.tearDown()
  
  

class TestCerrado(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()
    options = webdriver.ChromeOptions()
    options.headless = True
    self.driver = webdriver.Chrome(options=options)
    super().setUp()

    self.user = User.objects.filter(username="noadmin").first()

    self.q1 = Question(desc='Question #1')
    self.q1.save()
    self.v1 = Voting(name='Voting #1', question=self.q1, start_date=timezone.now(), end_date=timezone.now())
    self.v1.save()
    self.c1 = Census(voter_id=self.user.id, voting_id=self.v1.id)
    self.c1.save()

    self.q2 = Question(desc='Question #2')
    self.q2.save()
    self.v2 = Voting(name='Voting #2', question=self.q2, start_date=timezone.now())
    self.v2.save()
    self.c2 = Census(voter_id=self.user.id, voting_id=self.v2.id)
    self.c2.save()

    self.q3 = Question(desc='Question #3')
    self.q3.save()
    self.v3 = Voting(name='Voting #3', question=self.q3)
    self.v3.save()
    self.c3 = Census(voter_id=self.user.id, voting_id=self.v3.id)
    self.c3.save()
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()
    self.base.tearDown()
  

class TestAbierto(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()
    options = webdriver.ChromeOptions()
    options.headless = True
    self.driver = webdriver.Chrome(options=options)
    super().setUp()

    self.user = User.objects.filter(username="noadmin").first()

    self.q1 = Question(desc='Question #1')
    self.q1.save()
    self.v1 = Voting(name='Voting #1', question=self.q1, start_date=timezone.now(), end_date=timezone.now())
    self.v1.save()
    self.c1 = Census(voter_id=self.user.id, voting_id=self.v1.id)
    self.c1.save()

    self.q2 = Question(desc='Question #2')
    self.q2.save()
    self.v2 = Voting(name='Voting #2', question=self.q2, start_date=timezone.now())
    self.v2.save()
    self.c2 = Census(voter_id=self.user.id, voting_id=self.v2.id)
    self.c2.save()

    self.q3 = Question(desc='Question #3')
    self.q3.save()
    self.v3 = Voting(name='Voting #3', question=self.q3)
    self.v3.save()
    self.c3 = Census(voter_id=self.user.id, voting_id=self.v3.id)
    self.c3.save()

    
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()
    self.base.tearDown()
  
  
    
class TestCreado(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()
    options = webdriver.ChromeOptions()
    options.headless = True
    self.driver = webdriver.Chrome(options=options)
    super().setUp()

    self.user = User.objects.filter(username="noadmin").first()

    self.q1 = Question(desc='Question #1')
    self.q1.save()
    self.v1 = Voting(name='Voting #1', question=self.q1, start_date=timezone.now(), end_date=timezone.now())
    self.v1.save()
    self.c1 = Census(voter_id=self.user.id, voting_id=self.v1.id)
    self.c1.save()

    self.q2 = Question(desc='Question #2')
    self.q2.save()
    self.v2 = Voting(name='Voting #2', question=self.q2, start_date=timezone.now())
    self.v2.save()
    self.c2 = Census(voter_id=self.user.id, voting_id=self.v2.id)
    self.c2.save()

    self.q3 = Question(desc='Question #3')
    self.q3.save()
    self.v3 = Voting(name='Voting #3', question=self.q3)
    self.v3.save()
    self.c3 = Census(voter_id=self.user.id, voting_id=self.v3.id)
    self.c3.save()
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()
    self.base.tearDown()
  
  
    