# Generated by Django 4.1 on 2023-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mixnet", "0004_auto_20180605_0842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mixnet",
            name="voting_id",
            field=models.PositiveIntegerField(verbose_name="voting_id"),
        ),
    ]
