# Generated by Django 4.1 on 2023-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20180921_1522"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name": "Vote"},
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted",
            field=models.DateTimeField(auto_now=True, verbose_name="voted"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter_id",
            field=models.PositiveIntegerField(verbose_name="voter_id"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voting_id",
            field=models.PositiveIntegerField(verbose_name="voting_id"),
        ),
    ]
